### ISSUE TITLE
Podspec

### ISSUE THREAD

**Issue by jeffreyjackson** [hugocampossousa/HCSStarRatingView#1]
Can we get a podspec? :grimacing: :beers:

**Comment by hugocampossousa** [comment]
Hi @jeffreyjackson! I don't use CocoaPods, but I can look at supporting it when I have a chance.

In the meanwhile, pull requests are more than welcome. :-)

**Comment by jeffreyjackson** [comment]
maybe i'll send along a PR soon :+1:

**Comment by hugocampossousa** [comment]
That would be awesome, thanks!

**Comment by rjgdesign** [comment]
Second this!

**Comment by hugocampossousa** [comment]
Podspec created. You should now be able to use this control with CocoaPods.

Big thanks to @ScottWarner and @vikmeup for helping out!

*Warning:* CocoaPods and IBDesignable don't seem to play along as expected. I don't use CocoaPods so I can't verify this, so please refer to @ScottWarner's comment for more information: https://github.com/hugocampossousa/HCSStarRatingView/pull/2#issuecomment-90134758.
