### ISSUE TITLE
setting value is not working

### ISSUE THREAD

**Issue by danipralea** [hugocampossousa/HCSStarRatingView#10]
Hello and thank you for your work.
I am trying to set the value with .value = ... but the stars don't fill up :(

Any clue on why does this happen?
Thanks

**Comment by hugocampossousa** [comment]
Hi @danipralea!

I see you closed the issue. Did you manage to get it to work?

**Comment by danipralea** [comment]
Yeah, it seems that I'm really close to being crazy. I was not setting the outlet for the star rating view.
Thank you so much for your reply!

**Comment by hugocampossousa** [comment]
Oh... Yeah, that happens to us all sooner or later :)
