### ISSUE TITLE
Interface Designer does not render the view

### ISSUE THREAD

**Issue by gklka** [hugocampossousa/HCSStarRatingView#11]
It throws the following error:

```
Main.storyboard: error: IB Designables: Failed to render instance of HCSStarRatingView: Failed to load designables from path (null)
```

I use the view with the following settings:
<img width="265" src="http://gk.lka.hu/x/Screen%20Shot%202015-08-08%20at%2018.22.55.png">

What could be the problem? How can I solve it?

**Comment by hugocampossousa** [comment]
Hi @gklka! That's weird!

Can you provide a sample project that maybe I could take a look at?

**Comment by gklka** [comment]
Yes, here it is:
http://gk.lka.hu/x/StarTest.zip

**Comment by hugocampossousa** [comment]
Thanks for noticing this @gklka. It's related to a known issue in CocoaPods.

This issue has been fixed in CocoaPods 0.36.1, but you need to add `use_frameworks!` to your podfile (before specifying your dependencies/targets). I added that to your podfile and everything worked! :+1: 

Your podfile, after changing, ended up like this:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'StarTest' do

pod "HCSStarRatingView", :git => 'https://github.com/hugocampossousa/HCSStarRatingView.git'

end

target 'StarTestTests' do

end
```

Thanks again! I'm going to add a note to my README about this.

**Comment by gklka** [comment]
Thank you, this works fine. The only caveat is, that it breaks one of my other pods. :)

**Comment by rahulmehndiratta** [comment]
It throws the following error:

    Failed to render instance of HCSStarRatingView: the bundle "$Product_Name)" couldn't  be loaded because its executable couldn't be Located
![screen shot 2015-12-02 at 5 14 58 pm](https://cloud.githubusercontent.com/assets/10243461/11530152/47d867e4-9918-11e5-9ad8-dd43342374b0.png)

**Comment by palanik1987** [comment]
Select the concerned view and uncheck "Inherit module from target" under identity inspector in Xcode. This should work
