### ISSUE TITLE
Push it to cocoapods?

### ISSUE THREAD

**Issue by f33chobits** [hugocampossousa/HCSStarRatingView#12]
Hi @hugocampossousa 
  I was always fail to find a nice rating view until I found this one. But it hasn't been pushed to cocoapods  yet so that we had to specify the git address after 'pod'. Is there a spefific reason why?

**Comment by hugocampossousa** [comment]
Hi @f33chobits!
I'm in the process of doing that... just haven't had the time to finish it.

Thanks for reaching out! I'll post a comment here and close the issue once I'm done. :+1:

**Comment by f33chobits** [comment]
:+1: 
Thanks

**Comment by hugocampossousa** [comment]
Done: https://cocoapods.org/pods/HCSStarRatingView
