### ISSUE TITLE
New tag version

### ISSUE THREAD

**Issue by filipandrei87** [hugocampossousa/HCSStarRatingView#4]
Hi. Can you release a new version without using IB_DESIGNABLE?
Apple has released a huge bug in Xcode 6.3 ( http://stackoverflow.com/questions/29544738/xcode-6-3-freezes-hangs-after-opening-xib-file ) and this causes the storyboard to freeze.

Might help some users until Apple decides to fix their mistakes.

**Comment by hugocampossousa** [comment]
Hi @filipandrei87!

First of all, thanks for the feedback and suggestion.

I would recommend using Xcode 6.2 until this issue gets fixed.

If that's not possible, you can temporarily edit the header file to remove IB_DESIGNABLE until the fix comes through.

(if you're using CocoaPods, the easiest solution might be to fork this repo, make the change you want and update your podspec to temporarily point to your fork)
