### ISSUE TITLE
Use custom image?

### ISSUE THREAD

**Issue by Piero87** [hugocampossousa/HCSStarRatingView#7]
Hi this library is amazing, i have only a question, i have a custom image of a star, it's possible to use it in this library?

**Comment by hugocampossousa** [comment]
Hi @Piero87!

I'm sorry, but this library draws the star directly.

You can subclass it and override `-(void)_drawStarWithFrame:(CGRect)frame tintColor:(UIColor*)tintColor highlighted:(BOOL)highlighted` if you want it to draw anything else other than a star.

For example, you could use that method to draw your custom image for both normal and highlighted modes.

PS: I may consider supporting custom images in the future, but for now the idea is to keep it as light and clean as possible.

**Comment by Piero87** [comment]
ok thanks!

**Comment by Ponf** [comment]
My implementation of custom images in HCSStarRatingView subclass:

``` objc
- (void)_drawStarWithFrame:(CGRect)frame tintColor:(UIColor*)tintColor highlighted:(BOOL)highlighted{
    UIImageView *starView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:highlighted ?  NL(@"rating-full-heart") : NL(@"rating-empty-heart")]];
    starView.frame = frame;
    [self addSubview:starView];
}

- (void)_drawHalfStarWithFrame:(CGRect)frame tintcolor:(UIColor *)tintColor highlighted:(BOOL)highlighted {
    UIImageView *starView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:NL(@"rating-half-heart")]];
    starView.frame = frame;
    [self addSubview:starView];
}

- (void)drawRect:(CGRect)rect {
    [self.subviews makeObjectsPerformSelector: @selector(removeFromSuperview)];
    [super drawRect:rect];
}
```

I hope it will be helpful.

**Comment by hugocampossousa** [comment]
Thanks for that @Ponf!

Seeing this makes me reconsider supporting custom images... :-)

**Comment by hugocampossousa** [comment]
I added support for custom images in the latest version.
