### ISSUE TITLE
Minimum value option isn't respected

### ISSUE THREAD

**Issue by almassapargali** [hugocampossousa/HCSStarRatingView#9]
Hello, I've created one and set minimum value to1. Yet if you swipe over to left border of view, view shows 0 stars highlighted, but value is still 1.0.

I've looked around, but not exactly sure where to make change. Maybe we should use `setValue:` inside `_handleTouch` and check if it's smaller than minimum here?

**Comment by niccey** [comment]
I am having the same issue and would be happy to see a fix.

**Comment by niccey** [comment]
@almassapargali As you said, checking for the minimum value inside _handleTouch seems to fix it to me.

For example by inserting this line before ```[self setNeedsDisplay];```:
```
_value = self.value;
```
which does effectively this as defined in the value getter (adjusts for minimum and maximum value):
```
_value = MIN(MAX(_value, _minimumValue), _maximumValue);
```

**Comment by almassapargali** [comment]
@hugocampossousa hello, here is my change https://github.com/almassapargali/HCSStarRatingView/commit/207c5beff1d3ca7d810e955ec204b92117f1edff. Let me know if I should send PR.
